spring.application.name=jobboard
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/job_board_db
spring.datasource.username=postgres
spring.datasource.password=srujan

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
