spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
server.forward-headers-strategy=framework
server.error.include-message=never
server.error.include-stacktrace=never
logging.level.root=INFO
logging.level.com.globalco.jobboard=INFO
