package com.globalco.jobboard.dto.response;

import com.globalco.jobboard.entity.UserRole;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * DTO representing user details for API responses.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Response details of a registered user profile")
public class UserResponseDTO {

    @Schema(description = "Unique surrogate UUID generated by the system", example = "a2c13d8b-4b10-44be-8b22-832679f22579")
    private UUID id;

    @Schema(description = "User email address", example = "jane.doe@example.com")
    private String email;

    @Schema(description = "User first name", example = "Jane")
    private String firstName;

    @Schema(description = "User last name", example = "Doe")
    private String lastName;

    @Schema(description = "User contact phone number", example = "+15550199")
    private String phoneNumber;

    @Schema(description = "Account system access role", example = "SEEKER")
    private UserRole role;

    @Schema(description = "Active status of the user profile", example = "true")
    private Boolean isActive;

    @Schema(description = "Timestamp when the user account was registered")
    private Instant createdAt;

    @Schema(description = "Timestamp when the user account metadata was last modified")
    private Instant updatedAt;
}
